[package]
name = "tweaks"
version = "0.3.0"
edition = "2024"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
almost = "=0.2.0"
thiserror = "=2.0.17"
xplm = "=0.4.2"

[lints.clippy]
pedantic = "warn"
